In [ ]:
import pandas as pd
import pickle
import numpy as np
import nltk
import re
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
data = pd.read_csv('/content/tdata.csv.xls')
data

index                                             Review Rating
0          1  ok nothing special charge diamond member hilto...    Neg
1          3  unique, great stay, wonderful time hotel monac...    Pos
2          4  great stay great stay, went seahawk game aweso...    Pos
3          5  love monaco staff husband stayed hotel crazy w...    Pos
4          6  cozy stay rainy city, husband spent 7 nights m...    Pos
...      ...                                                ...    ...
12263  20485  not impressed unfriendly staff checked asked h...    Neg
12264  20486  best kept secret 3rd time staying charm, not 5...    Pos
12265  20488  ok just looks nice modern outside, desk staff ...    Neg
12266  20489  hotel theft ruined vacation hotel opened sept ...    Neg
12267  20490  people talking, ca n't believe excellent ratin...    Neg

[12268 rows x 3 columns]

In [ ]:
dataone=data.iloc[0:,1:]
dataone

Review Rating
0      ok nothing special charge diamond member hilto...    Neg
1      unique, great stay, wonderful time hotel monac...    Pos
2      great stay great stay, went seahawk game aweso...    Pos
3      love monaco staff husband stayed hotel crazy w...    Pos
4      cozy stay rainy city, husband spent 7 nights m...    Pos
...                                                  ...    ...
12263  not impressed unfriendly staff checked asked h...    Neg
12264  best kept secret 3rd time staying charm, not 5...    Pos
12265  ok just looks nice modern outside, desk staff ...    Neg
12266  hotel theft ruined vacation hotel opened sept ...    Neg
12267  people talking, ca n't believe excellent ratin...    Neg

[12268 rows x 2 columns]

In [ ]:
Reviews=[]


In [ ]:
stemming = PorterStemmer()

In [ ]:
for i in range(12268):
  review = data['Review'][i]
  review = re.sub('[^a-zA-Z]',' ',review)
  review = review.lower()
  review = review.split()
  review = [word for word in review if word not in set(stopwords.words('english'))]
  review = [stemming.stem(word) for word in review]
  review = ' '.join(review)
  Reviews.append(review)

In [ ]:
print(Reviews[0:20])

['ok noth special charg diamond member hilton decid chain shot th anniversari seattl start book suit paid extra websit descript suit bedroom bathroom standard hotel room took print reserv desk show said thing like tv couch ect desk clerk told oh mix suit descript kimpton websit sorri free breakfast got kid embassi suit sit room bathroom bedroom unlik kimpton call suit day stay offer correct fals advertis send kimpton prefer guest websit email ask failur provid suit advertis websit reserv descript furnish hard copi reserv printout websit desk manag duti repli solut send email trip guest survey follow email mail guess tell concern guest staff rang indiffer help ask desk good breakfast spot neighborhood hood told hotel gee best breakfast spot seattl block away conveni hotel know exist arriv late night pm insid run bellman busi chate cell phone help bag prior arriv email hotel inform th anniversari half realli picki want make sure good got nice email say like deliv bottl champagn chocol co

In [ ]:
data

index                                             Review Rating
0          1  ok nothing special charge diamond member hilto...    Neg
1          3  unique, great stay, wonderful time hotel monac...    Pos
2          4  great stay great stay, went seahawk game aweso...    Pos
3          5  love monaco staff husband stayed hotel crazy w...    Pos
4          6  cozy stay rainy city, husband spent 7 nights m...    Pos
...      ...                                                ...    ...
12263  20485  not impressed unfriendly staff checked asked h...    Neg
12264  20486  best kept secret 3rd time staying charm, not 5...    Pos
12265  20488  ok just looks nice modern outside, desk staff ...    Neg
12266  20489  hotel theft ruined vacation hotel opened sept ...    Neg
12267  20490  people talking, ca n't believe excellent ratin...    Neg

[12268 rows x 3 columns]

In [ ]:
dataone

Review Rating
0      ok nothing special charge diamond member hilto...    Neg
1      unique, great stay, wonderful time hotel monac...    Pos
2      great stay great stay, went seahawk game aweso...    Pos
3      love monaco staff husband stayed hotel crazy w...    Pos
4      cozy stay rainy city, husband spent 7 nights m...    Pos
...                                                  ...    ...
12263  not impressed unfriendly staff checked asked h...    Neg
12264  best kept secret 3rd time staying charm, not 5...    Pos
12265  ok just looks nice modern outside, desk staff ...    Neg
12266  hotel theft ruined vacation hotel opened sept ...    Neg
12267  people talking, ca n't believe excellent ratin...    Neg

[12268 rows x 2 columns]

In [ ]:
dataone['Rating']=dataone['Rating'].replace({'Pos':1,'Neg':0})
print(dataone)

                                                  Review  Rating
0      ok nothing special charge diamond member hilto...       0
1      unique, great stay, wonderful time hotel monac...       1
2      great stay great stay, went seahawk game aweso...       1
3      love monaco staff husband stayed hotel crazy w...       1
4      cozy stay rainy city, husband spent 7 nights m...       1
...                                                  ...     ...
12263  not impressed unfriendly staff checked asked h...       0
12264  best kept secret 3rd time staying charm, not 5...       1
12265  ok just looks nice modern outside, desk staff ...       0
12266  hotel theft ruined vacation hotel opened sept ...       0
12267  people talking, ca n't believe excellent ratin...       0

[12268 rows x 2 columns]


In [ ]:
dataone

Review  Rating
0      ok nothing special charge diamond member hilto...       0
1      unique, great stay, wonderful time hotel monac...       1
2      great stay great stay, went seahawk game aweso...       1
3      love monaco staff husband stayed hotel crazy w...       1
4      cozy stay rainy city, husband spent 7 nights m...       1
...                                                  ...     ...
12263  not impressed unfriendly staff checked asked h...       0
12264  best kept secret 3rd time staying charm, not 5...       1
12265  ok just looks nice modern outside, desk staff ...       0
12266  hotel theft ruined vacation hotel opened sept ...       0
12267  people talking, ca n't believe excellent ratin...       0

[12268 rows x 2 columns]

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

count = CountVectorizer()

In [ ]:
x = count.fit_transform(Reviews).toarray()
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
y = dataone['Rating'].values
y

array([0, 1, 1, ..., 0, 0, 0])

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2,random_state=15)

In [ ]:
x.shape, y.shape

((12268, 27552), (12268,))

In [ ]:
xtrain.shape, xtest.shape

((9814, 27552), (2454, 27552))

In [ ]:
ytrain.shape, ytest.shape

((9814,), (2454,))

In [ ]:
with open('count_vectorizer.pkl', 'wb') as file:
    pickle.dump(count, file)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()
model.add(Dense(5000,activation='relu'))
model.add(Dense(6000,activation='relu'))
model.add(Dense(3000,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

In [ ]:
model.compile(loss='binary_crossentropy', optimizer='adam',metrics=['accuracy'])

In [ ]:
model. fit(xtrain,ytrain,epochs=25,batch_size=5,validation_data=(xtest,ytest))

Epoch 1/25
1963/1963 [==============================] - 82s 39ms/step - loss: 0.2460 - accuracy: 0.9341 - val_loss: 0.1612 - val_accuracy: 0.9613
Epoch 2/25
1963/1963 [==============================] - 73s 37ms/step - loss: 0.0836 - accuracy: 0.9814 - val_loss: 0.1647 - val_accuracy: 0.9633
Epoch 3/25
1963/1963 [==============================] - 75s 38ms/step - loss: 0.0689 - accuracy: 0.9876 - val_loss: 0.4342 - val_accuracy: 0.9515
Epoch 4/25
1963/1963 [==============================] - 75s 38ms/step - loss: 0.0543 - accuracy: 0.9908 - val_loss: 0.5227 - val_accuracy: 0.9588
Epoch 5/25
1963/1963 [==============================] - 73s 37ms/step - loss: 0.0307 - accuracy: 0.9952 - val_loss: 0.8646 - val_accuracy: 0.9641
Epoch 6/25
1963/1963 [==============================] - 73s 37ms/step - loss: 0.0275 - accuracy: 0.9978 - val_loss: 0.6372 - val_accuracy: 0.9597
Epoch 7/25
1963/1963 [==============================] - 73s 37ms/step - loss: 0.0164 - accuracy: 0.9967 - val_loss: 1.0757 -

In [ ]:
testdata= 'not so good'
testdata = re.sub('[^a-zA-Z]',' ',testdata)
testdata = testdata.lower()
testdata = testdata.split()
testdata = [word for word in testdata if word not in set(stopwords.words('english'))]
testdata = [stemming.stem(word) for word in testdata]
testdata = ' '.join(testdata)
testdata = count.transform([testdata]).toarray()
prediction = model.predict(testdata)
print(testdata)
print(prediction)
if prediction>0.5:
  print('Positive')
else:
  print('Negative')

1/1 [==============================] - 0s 19ms/step
[[0 0 0 ... 0 0 0]]
[[0.33171353]]
Negative
